### ISSUE TITLE
View for login users, sign up and forgot password.

### ISSUE THREAD

**Issue by d1eg0dev** [BC-MAY-21-ROR/proyecto-final-serenity-m22-pf-t1#24]
# REQUIREMENTS
Create view for login users
Create view for sign up
Create view for forgot password

# DESIGN
(https://www.figma.com/file/iU9Y8Q1w218wy6SwLWtHCX/Serenity-%2F-Design-UI?node-id=0%3A1)

# Acceptance Criteria
List all required acceptance criteria
- [ ] Criteria 1
- [ ] Criteria 2

**Comment by EdwardMD** [comment]
Log in view for users (Desktop version), still working on polishing aspects such as object positioning, but it is fully functional.
![log_in](https://user-images.githubusercontent.com/93165352/179839855-8bbb03fe-eb0e-4669-9c9c-ad15db9790a7.png)


Sign Up for new users (Desktop view), same problem as the login view, still working in the position of the object. it´s fully functional too.
![sign_up](https://user-images.githubusercontent.com/93165352/179840111-fd503bc7-4fd4-4caa-8e4b-a1122267cb7d.png)


Forgot Password for users (Desktop View).
![forgot_password](https://user-images.githubusercontent.com/93165352/179840333-59919b90-d663-4ed7-a538-12842a2fd292.png)
