### ISSUE TITLE
Create dashboard

### ISSUE THREAD

**Issue by Jumaquba** [BC-MAY-21-ROR/proyecto-final-serenity-m22-pf-t1#39]

**Comment by d1eg0dev** [comment]
Main Dashboard for Serenity Project users. View with lateral menu (desktop view) cards and graphs, we are making changes in the next week for a better user experience 

![Screenshot 2022-07-18 at 18-37-29 Serenity - Dashboard](https://user-images.githubusercontent.com/103774119/179634520-8c37c41e-ddd3-428e-b3bd-3f2e88e44b39.png)

**Comment by acorzo** [comment]
GLTM, Just make sure that the backgroud of the side menu is light or like the serenity color palette.
